### ISSUE TITLE
New:Mirror ftp.acc.umu.se 

### ISSUE THREAD

**Issue by ZNikke** [PacBSD/pacweb#9]
* Mirror domain name
  * ftp.acc.umu.se
* Geographical location of the mirror (country)
  * Umeå, Sweden, Europe
* URLs for supported access methods (http(s), rsync) (no ftp)
  * http://ftp.acc.umu.se/mirror/pacbsd.org/
  * https://ftp.acc.umu.se/mirror/pacbsd.org/
  * rsync://ftp.acc.umu.se/mirror/pacbsd.org/
* Your mirror's available bandwidth
  * 20 Gbps
* An administrative contact email
  * ftp-adm@acc.umu.se
* An alternative administrative contact email (optional)
  * none
* Sync ISOs (yes/no)
  * yes (we pull packages.pacbsd.org::packages/ which seem to contain the isos)
* Path to lastupdate file (if other than http(s)://mirror.domainname.tld/.../lastupdate)
  * default

**Comment by ZNikke** [comment]
Note that as a non-contributor I don't seem to be allowed to add the New:Mirror label in order to adhere to the instructions on http://wiki.pacbsd.org/index.php/DeveloperWiki:NewMirrors#Create_a_Feature_Request ...

I suggest that the instructions are reworded so it's possible to follow them without becoming a contributor first :-)

**Comment by ZNikke** [comment]
Standard caveats from our template:

*NOTE* that the cluster is highly optimized for http/https, so despite 
the name we prefer to not publish clickable FTP links. Those who 
really needs to use FTP can usually figure it out from the site name!

*NOTE2* that the cluster uses redirects to offload requests for large
files to dedicated large-file offload targets. Mechanisms that check
mirror status must not treat this as an error.

**Comment by vendion** [comment]
> Note that as a non-contributor I don't seem to be allowed to add the New:Mirror label in order to adhere to the instructions on http://wiki.pacbsd.org/index.php/DeveloperWiki:NewMirrors#Create_a_Feature_Request ...
>
> I suggest that the instructions are reworded so it's possible to follow them without becoming a contributor first :-)

Thanks for pointing that out, this is a restriction on GitHub's side that wasn't accounted for when that wiki page was done. Thank you for putting it in the subject though, that may be a good work around since labels are limited in GitHub.

> NOTE that the cluster is highly optimized for http/https, so despite
the name we prefer to not publish clickable FTP links. Those who
really needs to use FTP can usually figure it out from the site name!

I'm sure this is something that you are required to state, but as our template states we don't allow FTP mirrors anyways so this won't be an issue.
